--- #YAML:1.0
name:               Test-Bot
version:            0.06
abstract:           Continuous integration bot for automatically running unit tests and notifying developers of failed tests
author:
    - Mischa Spiegelmock <revmischa@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Any::Moose:           0
    AnyEvent::IRC::Client:  0
    Class::MOP:           0
    DateTime:             0
    DateTime::Format::ISO8601:  0
    JSON:                 0
    MouseX::Getopt:       0
    MouseX::NativeTraits::ArrayRef:  0
    Plack::Request:       0
    TAP::Harness:         0
    Test::More:           0
    Twiggy::Server:       0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
